version: '3.1'
services:
#    mysql:
#        image: mysql:8.0
#        working_dir: /application
#        container_name: test-app-mysql
#        volumes:
#            - .:/application
#            - test-app-mysql-volume:/var/lib/mysql
#        environment:
#            - MYSQL_ROOT_PASSWORD=currency
#            - MYSQL_DATABASE=currency
#            - MYSQL_USER=currency
#            - MYSQL_PASSWORD=currency
#        ports:
#            - '3306:3306'

    webserver:
        image: nginx:alpine
        working_dir: /application
        container_name: test-app-nginx
        depends_on:
            - php-fpm
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'

    node:
        image: node:18.0-alpine
#        image: node:16-alpine
        container_name: test-app-node
        working_dir: /application
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/application
        entrypoint: [ 'npm', 'run', 'dev' ]
        tty: true
        ports:
            - "5173:5173"
            - "3000:3000"
            - "3001:3001"
        depends_on:
            - php-fpm

    php-fpm:
#        image: falcon4ik007/-fpm-alpine
        image: php:8.2.6-fpm-alpine
        #build: phpdocker/php-fpm
        #platform: linux/amd64
        container_name: test-app-php-fpm
        working_dir: /application
        environment:
            XDEBUG_MODE: "coverage"
        security_opt:
            - seccomp=unconfined
#        depends_on:
#            - mysql
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

volumes:
    test-app-mysql-volume:
    test-app-mysql-test-volume:
